In [1]:
# Libraries
import xarray as xr # For viewing NetCDF files
import rasterio 
import numpy as np
import rioxarray

In [ ]:
#### ssp2 2025: ############################################################################################################

In [2]:
# Load in data
ssp2_2025 = './data/projected_precip/precip_ssp2_2025/GISS-E2-1-G_ssp2_2025_pr.nc'
xrds = xr.open_dataset(ssp2_2025, engine = 'netcdf4') 
print(f"Shape: {xrds.data_vars['pr'].shape}")
xrds

Shape: (365, 105, 237)


<xarray.Dataset>
Dimensions:  (lon: 237, time: 365, lat: 105)
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2025-01-01 12:00:00 ... 2025-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Data variables:
    pr       (time, lat, lon) float32 ...
Attributes: (12/27)
    _NCProperties:         version=2,netcdf=4.8.1,hdf5=1.12.2
    cmip6_source_id:       GISS-E2-1-G
    cmip6_institution_id:  NASA-GISS
    cmip6_license:         CC0 1.0
    activity:              NEX-GDDP-CMIP6
    Conventions:           CF-1.7
    ...                    ...
    tracking_id:           d02d765a-ba85-4768-987b-edfe8dfb84b4
    History:               Translated to CF-1.0 Conventions by Netcdf-Java CD...
    geospatial_lat_min:    24.0
    geospatial_lat_max:    50.25
    geospatial_lon_min:    -125.0
    geospatial_lon_max:    -65.75

In [3]:
# Prcp var
xrds['pr']

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
[9083025 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2025-01-01 12:00:00 ... 2025-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Attributes:
    standard_name:  precipitation_flux
    long_name:      Precipitation
    units:          kg m-2 s-1
    comment:        includes both liquid and solid phases
    cell_methods:   area: time: mean
    cell_measures:  area: areacella

In [4]:
# Convert units to mm/day - https://stackoverflow.com/questions/75662038/convert-units-in-a-netcdf-file-efficiently
pr_mm_day = xrds['pr'] * 86400
pr_mm_day

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
array([[[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [4.32447229e-01, 4.50878641e-01, 4.33076343e-01, ...,
                    nan,            nan,            nan],
        [3.56030400e-01, 3.80167099e-01, 3.84530587e-01, ...,
                    nan,            nan,            nan],
        [2.81670254e-01, 3.08834359e-01, 3.40650302e-01, ...,
         0.00000000e+00, 0.00000000e+00,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
...
        [3.24187642e-01, 2.44802421e-01, 1.67876371e-01, ...,
                    nan,            nan,            nan],
        [3.78299401e-01, 2.83493751e-01, 1.95480231e-01, ...,
                    nan,            nan,            nan],
        [4.03953722e-01, 3.04454703e-01, 2.21573305e-01, ...,
         0.00000000e+00, 4.17777350e-02,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [2.51016316e+01, 2.43594258e+01, 2.20996362e+01, ...,
                    nan,            nan,            nan],
        [2.11331156e+01, 2.11293639e+01, 2.02905307e+01, ...,
                    nan,            nan,            nan],
        [1.71601149e+01, 1.77385265e+01, 1.86717492e+01, ...,
         3.86040170e+00, 3.68144786e+00,            nan]]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2025-01-01 12:00:00 ... 2025-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [5]:
# Calculate mean prcp rate (for all days)
pr_2025_mean_prcp_rate = pr_mm_day.mean(dim = 'time')
print(f'Shape: {pr_2025_mean_prcp_rate.shape}')
pr_2025_mean_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [7.00059249, 6.37513053, 5.45118235, ...,        nan,        nan,
               nan],
       [6.40256766, 5.99054819, 5.39170483, ...,        nan,        nan,
               nan],
       [5.65046525, 5.36170953, 5.23660339, ..., 3.73256364, 3.68423249,
               nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [6]:
# Calculate sd of prcp rate
pr_2025_sd_prcp_rate = pr_mm_day.std(dim = 'time')
print(f'Shape: {pr_2025_sd_prcp_rate.shape}')
pr_2025_sd_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [10.2226254 ,  9.36289238,  8.02098112, ...,         nan,
                nan,         nan],
       [ 9.23424832,  8.66933289,  7.82417159, ...,         nan,
                nan,         nan],
       [ 8.06794732,  7.69866756,  7.56650818, ...,  6.76515405,
         6.74025425,         nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [7]:
# Export mean prcp rate as geotiff
out_mean_prcp_ssp2_2025 = './data/projected_precip/precip_ssp2_2025/ssp2_2025_prcp_rate.tif'

# Add CRS
pr_2025_mean_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2025_mean_prcp_rate.rio.to_raster(out_mean_prcp_ssp2_2025)


# Export mean sd as geotiff
out_sd_prcp_ssp2_2025 = './data/projected_precip/precip_ssp2_2025/ssp2_2025_standard_dev_prcp_rate.tif'

# Add CRS
pr_2025_sd_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2025_sd_prcp_rate.rio.to_raster(out_sd_prcp_ssp2_2025)

In [8]:
# Close file
xrds.close()

In [ ]:
#### ssp2 2050: ############################################################################################################

In [9]:
# Load in data
ssp2_2050 = './data/projected_precip/precip_ssp2_2050/GISS-E2-1-G_ssp2_2050_pr.nc'
xrds = xr.open_dataset(ssp2_2050, engine = 'netcdf4') 
print(f"Shape: {xrds.data_vars['pr'].shape}")
xrds

Shape: (365, 105, 237)


<xarray.Dataset>
Dimensions:  (lon: 237, time: 365, lat: 105)
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Data variables:
    pr       (time, lat, lon) float32 ...
Attributes: (12/27)
    _NCProperties:         version=2,netcdf=4.8.1,hdf5=1.12.2
    cmip6_source_id:       GISS-E2-1-G
    cmip6_institution_id:  NASA-GISS
    cmip6_license:         CC0 1.0
    activity:              NEX-GDDP-CMIP6
    Conventions:           CF-1.7
    ...                    ...
    tracking_id:           ed63deef-e3ec-453c-838e-f3985905799a
    History:               Translated to CF-1.0 Conventions by Netcdf-Java CD...
    geospatial_lat_min:    24.0
    geospatial_lat_max:    50.25
    geospatial_lon_min:    -125.0
    geospatial_lon_max:    -65.75

In [10]:
# Prcp var
xrds['pr']

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
[9083025 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Attributes:
    standard_name:  precipitation_flux
    long_name:      Precipitation
    units:          kg m-2 s-1
    comment:        includes both liquid and solid phases
    cell_methods:   area: time: mean
    cell_measures:  area: areacella

In [11]:
# Convert units to mm/day - https://stackoverflow.com/questions/75662038/convert-units-in-a-netcdf-file-efficiently
pr_mm_day = xrds['pr'] * 86400
pr_mm_day

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
array([[[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [5.13776068e+00, 4.15181376e+00, 3.11608053e+00, ...,
                    nan,            nan,            nan],
        [4.20392321e+00, 3.52641796e+00, 2.83579262e+00, ...,
                    nan,            nan,            nan],
        [3.30161280e+00, 2.88936807e+00, 2.58400454e+00, ...,
         5.35640300e-02, 4.74380735e-02,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
...
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         3.60203739e+00, 3.26588043e+00,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [4.13029060e+00, 3.35205918e+00, 2.53103023e+00, ...,
                    nan,            nan,            nan],
        [3.39486283e+00, 2.77190554e+00, 2.15721804e+00, ...,
                    nan,            nan,            nan],
        [2.68101480e+00, 2.20055620e+00, 1.81721143e+00, ...,
         6.04702954e+00, 6.18937940e+00,            nan]]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [12]:
# Calculate mean prcp rate (for all days)
pr_2050_ssp2_mean_prcp_rate = pr_mm_day.mean(dim = 'time')
print(f'Shape: {pr_2050_ssp2_mean_prcp_rate.shape}')
pr_2050_ssp2_mean_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [7.62227889, 6.96632559, 6.01690471, ...,        nan,        nan,
               nan],
       [7.04069247, 6.60292755, 5.9833368 , ...,        nan,        nan,
               nan],
       [6.29231449, 5.96883994, 5.83124761, ..., 2.89146733, 2.82636239,
               nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [13]:
# Calculate sd of prcp rate
pr_2050_ssp2_sd_prcp_rate = pr_mm_day.std(dim = 'time')
print(f'Shape: {pr_2050_ssp2_sd_prcp_rate.shape}')
pr_2050_ssp2_sd_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [10.57762948,  9.74625182,  8.45796648, ...,         nan,
                nan,         nan],
       [ 9.75273363,  9.21374619,  8.41625776, ...,         nan,
                nan,         nan],
       [ 8.71815668,  8.36868732,  8.28327476, ...,  4.98529476,
         4.8882638 ,         nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [14]:
# Export mean prcp rate as geotiff
out_mean_prcp_ssp2_2050 = './data/projected_precip/precip_ssp2_2050/ssp2_2050_prcp_rate.tif'

# Add CRS
pr_2050_ssp2_mean_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2050_ssp2_mean_prcp_rate.rio.to_raster(out_mean_prcp_ssp2_2050)


# Export mean sd as geotiff
out_sd_prcp_ssp2_2050 = './data/projected_precip/precip_ssp2_2050/ssp2_2050_standard_dev_prcp_rate.tif'

# Add CRS
pr_2050_ssp2_sd_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2050_ssp2_sd_prcp_rate.rio.to_raster(out_sd_prcp_ssp2_2050)

In [15]:
# Close file
xrds.close()

In [ ]:
#### ssp5 2050: ############################################################################################################

In [16]:
# Load in data
ssp5_2050 = './data/projected_precip/precip_ssp5_2050/GISS-E2-1-G_ssp5_2050_pr.nc'
xrds = xr.open_dataset(ssp5_2050, engine = 'netcdf4') 
print(f"Shape: {xrds.data_vars['pr'].shape}")
xrds

Shape: (365, 105, 237)


<xarray.Dataset>
Dimensions:  (lon: 237, time: 365, lat: 105)
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Data variables:
    pr       (time, lat, lon) float32 ...
Attributes: (12/27)
    _NCProperties:         version=2,netcdf=4.8.1,hdf5=1.12.2
    cmip6_source_id:       GISS-E2-1-G
    cmip6_institution_id:  NASA-GISS
    cmip6_license:         CC0 1.0
    activity:              NEX-GDDP-CMIP6
    Conventions:           CF-1.7
    ...                    ...
    tracking_id:           4a462adf-45bb-4aff-a2b5-f78596a4c335
    History:               Translated to CF-1.0 Conventions by Netcdf-Java CD...
    geospatial_lat_min:    24.0
    geospatial_lat_max:    50.25
    geospatial_lon_min:    -125.0
    geospatial_lon_max:    -65.75

In [17]:
# Prcp var
xrds['pr']

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
[9083025 values with dtype=float32]
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12
Attributes:
    standard_name:  precipitation_flux
    long_name:      Precipitation
    units:          kg m-2 s-1
    comment:        includes both liquid and solid phases
    cell_methods:   area: time: mean
    cell_measures:  area: areacella

In [18]:
# Convert units to mm/day - https://stackoverflow.com/questions/75662038/convert-units-in-a-netcdf-file-efficiently
pr_mm_day = xrds['pr'] * 86400
pr_mm_day

<xarray.DataArray 'pr' (time: 365, lat: 105, lon: 237)>
array([[[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [1.58575885e+00, 1.49341500e+00, 1.31873420e+00, ...,
                    nan,            nan,            nan],
        [1.15754415e+00, 1.11449674e+00, 1.03498310e+00, ...,
                    nan,            nan,            nan],
        [7.77310538e-01, 7.66888898e-01, 7.75422802e-01, ...,
         4.68411723e-01, 5.23800452e-01,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
...
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
                    nan,            nan,            nan],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
         1.41786330e+00, 1.38589855e+00,            nan]],

       [[           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        [           nan,            nan,            nan, ...,
                    nan,            nan,            nan],
        ...,
        [8.71569025e+00, 7.47005478e+00, 6.00904443e+00, ...,
                    nan,            nan,            nan],
        [7.00019777e+00, 6.17500423e+00, 5.26174726e+00, ...,
                    nan,            nan,            nan],
        [5.37453142e+00, 4.90006992e+00, 4.58460568e+00, ...,
         4.17518182e-01, 4.11345775e-01,            nan]]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * time     (time) object 2050-01-01 12:00:00 ... 2050-12-31 12:00:00
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [19]:
# Calculate mean prcp rate (for all days)
pr_2050_ssp5_mean_prcp_rate = pr_mm_day.mean(dim = 'time')
print(f'Shape: {pr_2050_ssp5_mean_prcp_rate.shape}')
pr_2050_ssp5_mean_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [6.92036306, 6.33021551, 5.47545722, ...,        nan,        nan,
               nan],
       [6.33544715, 5.95595527, 5.41062184, ...,        nan,        nan,
               nan],
       [5.61419192, 5.34208731, 5.23759602, ..., 3.10545344, 3.05245833,
               nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [20]:
# Calculate sd of prcp rate
pr_2050_ssp5_sd_prcp_rate = pr_mm_day.std(dim = 'time')
print(f'Shape: {pr_2050_ssp5_sd_prcp_rate.shape}')
pr_2050_ssp5_sd_prcp_rate

Shape: (105, 237)


<xarray.DataArray 'pr' (lat: 105, lon: 237)>
array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       ...,
       [11.15729698, 10.27124351,  8.90355958, ...,         nan,
                nan,         nan],
       [10.07269435,  9.54088234,  8.73800457, ...,         nan,
                nan,         nan],
       [ 8.82960252,  8.52930589,  8.49742146, ...,  5.2617054 ,
         5.16978096,         nan]])
Coordinates:
  * lon      (lon) float64 235.1 235.4 235.6 235.9 ... 293.4 293.6 293.9 294.1
  * lat      (lat) float64 24.12 24.38 24.62 24.88 ... 49.38 49.62 49.88 50.12

In [21]:
# Export mean prcp rate as geotiff
out_mean_prcp_ssp5_2050 = './data/projected_precip/precip_ssp5_2050/ssp5_2050_prcp_rate.tif'

# Add CRS
pr_2050_ssp5_mean_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2050_ssp5_mean_prcp_rate.rio.to_raster(out_mean_prcp_ssp5_2050)


# Export mean sd as geotiff
out_sd_prcp_ssp5_2050 = './data/projected_precip/precip_ssp5_2050/ssp5_2050_standard_dev_prcp_rate.tif'

# Add CRS
pr_2050_ssp5_sd_prcp_rate.rio.write_crs('epsg:4326', inplace = True)

# Write
pr_2050_ssp5_sd_prcp_rate.rio.to_raster(out_sd_prcp_ssp5_2050)

In [22]:
# Close file
xrds.close()